/* Banco de exercicios — cada item traz execucao, erros comuns e video */
const EX = [
  // ---------------- PEITO ----------------
  { id:'supino-reto-barra', nome:'Supino reto com barra', grupo:'peito', tipo:'composto', req:'academia', nivel:1,
    musculos:'Peitoral maior, tríceps, deltoide anterior',
    q:'supino reto com barra execução correta',
    exec:['Deite no banco com os pés firmes no chão e as escápulas apertadas uma contra a outra.','Segure a barra um pouco mais aberto que a largura dos ombros.','Desça a barra controlado até encostar de leve na linha do mamilo.','Empurre de volta sem travar o cotovelo no topo.'],
    erros:['Quicar a barra no peito.','Levantar o quadril do banco.','Abrir o cotovelo a 90° em relação ao tronco (mire ~45°).'] },
  { id:'supino-inclinado-halteres', nome:'Supino inclinado com halteres', grupo:'peito', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Peitoral superior, deltoide anterior, tríceps',
    q:'supino inclinado com halteres execução',
    exec:['Ajuste o banco entre 30° e 45°.','Comece com os halteres na linha do peito, palmas para frente.','Empurre para cima aproximando levemente os halteres.','Desça controlado até sentir o peito alongar.'],
    erros:['Inclinar o banco demais (vira exercício de ombro).','Bater os halteres no topo.','Descer rápido demais.'] },
  { id:'supino-reto-halteres', nome:'Supino reto com halteres', grupo:'peito', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Peitoral maior, tríceps, deltoide anterior',
    q:'supino reto com halteres execução correta',
    exec:['Deite com um halter em cada mão apoiado na coxa e leve-os ao peito.','Mantenha os punhos firmes e alinhados com o cotovelo.','Empurre para cima até quase estender o braço.','Desça até o halter ficar na linha do peito.'],
    erros:['Deixar o punho dobrar para trás.','Descer além da amplitude confortável do ombro.'] },
  { id:'crucifixo-halteres', nome:'Crucifixo com halteres', grupo:'peito', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Peitoral maior',
    q:'crucifixo com halteres execução correta',
    exec:['Deite no banco com os halteres estendidos acima do peito.','Mantenha um cotovelo levemente dobrado e fixo nesse ângulo.','Abra os braços em arco até sentir o peito alongar.','Volte fazendo o movimento de abraçar.'],
    erros:['Dobrar e estender o cotovelo (vira supino).','Usar carga pesada demais e perder o arco.'] },
  { id:'crossover-polia', nome:'Crossover na polia', grupo:'peito', tipo:'isolado', req:'academia', nivel:2,
    musculos:'Peitoral maior, principalmente porção interna',
    q:'crossover polia peito execução correta',
    exec:['Posicione as polias acima da cabeça e dê um passo à frente.','Incline o tronco levemente e mantenha o cotovelo semiflexionado.','Traga as mãos à frente do corpo, cruzando levemente.','Volte controlado sentindo o peito abrir.'],
    erros:['Usar o tronco para empurrar.','Estender o cotovelo no meio do movimento.'] },
  { id:'flexao-de-braco', nome:'Flexão de braço', grupo:'peito', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Peitoral, tríceps, core',
    q:'flexão de braço execução correta',
    exec:['Mãos um pouco mais abertas que os ombros, corpo em linha reta.','Contraia glúteo e abdômen para não deixar o quadril cair.','Desça até o peito quase encostar no chão.','Empurre o chão para longe até estender os braços.'],
    erros:['Quadril caindo ou empinado.','Cotovelo abrindo a 90°.','Não descer a amplitude toda.'] },
  { id:'flexao-inclinada', nome:'Flexão com mãos elevadas', grupo:'peito', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Peitoral, tríceps, core',
    q:'flexão de braço inclinada iniciante execução',
    exec:['Apoie as mãos numa mesa, banco ou parede.','Quanto mais alto o apoio, mais fácil o exercício.','Mantenha o corpo em linha reta da cabeça ao calcanhar.','Desça até o peito quase tocar o apoio e empurre.'],
    erros:['Apoiar em superfície instável.','Deixar o quadril cair.'] },
  { id:'flexao-diamante', nome:'Flexão diamante', grupo:'peito', tipo:'composto', req:'nenhum', nivel:2,
    musculos:'Tríceps, peitoral interno',
    q:'flexão diamante execução correta',
    exec:['Junte as mãos formando um triângulo embaixo do peito.','Mantenha o cotovelo colado ao corpo.','Desça até o peito tocar as mãos.','Empurre de volta mantendo o core firme.'],
    erros:['Abrir o cotovelo.','Apoiar as mãos muito à frente do peito.'] },
  { id:'mergulho-paralelas', nome:'Mergulho nas paralelas', grupo:'peito', tipo:'composto', req:'academia', nivel:2,
    musculos:'Peitoral inferior, tríceps, deltoide anterior',
    q:'mergulho paralelas execução correta',
    exec:['Suba nas barras com os braços estendidos.','Incline o tronco à frente para focar peito (vertical foca tríceps).','Desça até o ombro ficar na linha do cotovelo.','Suba empurrando as barras.'],
    erros:['Descer fundo demais e forçar o ombro.','Balançar as pernas para ganhar impulso.'] },
  { id:'peck-deck', nome:'Peck deck (voador)', grupo:'peito', tipo:'isolado', req:'academia', nivel:1,
    musculos:'Peitoral maior',
    q:'peck deck voador máquina execução correta',
    exec:['Ajuste o banco para que as pegadas fiquem na linha do peito.','Mantenha as costas apoiadas e o cotovelo levemente flexionado.','Feche os braços à frente contraindo o peito.','Volte controlado sem deixar os pesos baterem.'],
    erros:['Levantar as costas do apoio.','Usar impulso e soltar a volta.'] },

  // ---------------- COSTAS ----------------
  { id:'barra-fixa', nome:'Barra fixa', grupo:'costas', tipo:'composto', req:'academia', nivel:2,
    musculos:'Dorsal, bíceps, romboides',
    q:'barra fixa execução correta pegada pronada',
    exec:['Pegada pronada um pouco mais aberta que os ombros.','Puxe as escápulas para baixo antes de dobrar o cotovelo.','Suba até o queixo passar da barra.','Desça controlado até quase estender o braço.'],
    erros:['Usar impulso de perna sem necessidade.','Não descer a amplitude completa.'] },
  { id:'puxada-frente', nome:'Puxada frontal no pulley', grupo:'costas', tipo:'composto', req:'academia', nivel:1,
    musculos:'Dorsal, bíceps, romboides',
    q:'puxada frontal pulley execução correta',
    exec:['Ajuste o apoio das coxas e segure a barra mais aberto que os ombros.','Incline o tronco levemente para trás e estufe o peito.','Puxe a barra até a parte alta do peito.','Volte controlado deixando as escápulas subirem.'],
    erros:['Puxar atrás da nuca.','Jogar o tronco para trás para vencer a carga.'] },
  { id:'remada-curvada', nome:'Remada curvada com barra', grupo:'costas', tipo:'composto', req:'academia', nivel:2,
    musculos:'Dorsal, romboides, trapézio, lombar',
    q:'remada curvada com barra execução correta',
    exec:['Pés na largura do quadril, joelho levemente flexionado.','Incline o tronco a ~45° mantendo a coluna neutra.','Puxe a barra em direção ao umbigo.','Desça controlado sem arredondar as costas.'],
    erros:['Arredondar a lombar.','Levantar o tronco a cada repetição.'] },
  { id:'remada-serrote', nome:'Remada serrote (unilateral)', grupo:'costas', tipo:'composto', req:'halteres', nivel:1, unilateral:true,
    musculos:'Dorsal, romboides, bíceps',
    q:'remada serrote halter execução correta',
    exec:['Apoie um joelho e uma mão no banco, coluna paralela ao chão.','Segure o halter com o braço estendido.','Puxe o halter em direção ao quadril, cotovelo colado.','Desça controlado sentindo a dorsal alongar.'],
    erros:['Girar o tronco para puxar mais peso.','Puxar com o cotovelo aberto.'] },
  { id:'remada-baixa', nome:'Remada baixa na polia', grupo:'costas', tipo:'composto', req:'academia', nivel:1,
    musculos:'Dorsal, romboides, trapézio médio',
    q:'remada baixa polia execução correta',
    exec:['Sente com os pés apoiados e o joelho levemente flexionado.','Mantenha o tronco ereto e o peito estufado.','Puxe o triângulo até o abdômen, juntando as escápulas.','Volte controlado sem curvar as costas.'],
    erros:['Balançar o tronco para frente e para trás.','Encolher os ombros durante a puxada.'] },
  { id:'remada-elastico', nome:'Remada com elástico', grupo:'costas', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Dorsal, romboides, bíceps',
    q:'remada com elástico execução correta',
    exec:['Prenda o elástico em um ponto firme na altura do peito.','Segure as pontas com os braços estendidos e dê passos para trás até tensionar.','Puxe os cotovelos para trás juntando as escápulas.','Volte controlado mantendo a tensão.'],
    erros:['Deixar o elástico frouxo no início.','Puxar só com o braço, sem juntar as escápulas.'] },
  { id:'remada-invertida', nome:'Remada invertida (australiana)', grupo:'costas', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Dorsal, romboides, bíceps',
    q:'remada invertida australiana execução correta',
    exec:['Deite embaixo de uma mesa firme ou barra baixa.','Segure a borda com as mãos na largura dos ombros.','Mantenha o corpo reto e puxe o peito em direção à barra.','Desça controlado até estender os braços.'],
    erros:['Deixar o quadril cair.','Não encostar o peito perto da barra.'] },
  { id:'levantamento-terra', nome:'Levantamento terra', grupo:'costas', tipo:'composto', req:'academia', nivel:3,
    musculos:'Cadeia posterior inteira: lombar, glúteo, posterior de coxa, dorsal',
    q:'levantamento terra execução correta técnica',
    exec:['Barra sobre o meio do pé, pés na largura do quadril.','Segure a barra, peito estufado e coluna neutra.','Empurre o chão com os pés e suba a barra colada à perna.','Trave quadril e joelho no topo sem hiperestender a lombar.'],
    erros:['Arredondar a lombar na subida.','Afastar a barra do corpo.','Puxar com os braços em vez de empurrar o chão.'] },
  { id:'pullover-halter', nome:'Pullover com halter', grupo:'costas', tipo:'isolado', req:'halteres', nivel:2,
    musculos:'Dorsal, serrátil, peitoral',
    q:'pullover com halter execução correta',
    exec:['Deite no banco segurando um halter com as duas mãos sobre o peito.','Cotovelo levemente flexionado e fixo.','Leve o halter para trás da cabeça até sentir alongar.','Volte contraindo a dorsal.'],
    erros:['Descer demais e forçar o ombro.','Dobrar o cotovelo durante o movimento.'] },
  { id:'superman', nome:'Superman (extensão lombar)', grupo:'costas', tipo:'isolado', req:'nenhum', nivel:1,
    musculos:'Eretores da espinha, glúteo',
    q:'exercício superman lombar execução correta',
    exec:['Deite de barriga para baixo com braços estendidos à frente.','Levante braços, peito e pernas ao mesmo tempo.','Segure 2 segundos contraindo o glúteo e a lombar.','Desça controlado.'],
    erros:['Jogar a cabeça para trás.','Subir com impulso.'] },

  // ---------------- PERNAS ----------------
  { id:'agachamento-livre', nome:'Agachamento livre com barra', grupo:'pernas', tipo:'composto', req:'academia', nivel:2,
    musculos:'Quadríceps, glúteo, posterior de coxa, core',
    q:'agachamento livre execução correta técnica',
    exec:['Barra apoiada no trapézio, pés na largura dos ombros e pontas levemente abertas.','Inspire, trave o core e desça empurrando o quadril para trás.','Desça até a coxa ficar pelo menos paralela ao chão.','Suba empurrando o chão, joelho alinhado com o pé.'],
    erros:['Joelho colapsando para dentro.','Calcanhar saindo do chão.','Arredondar a lombar no fundo.'] },
  { id:'agachamento-goblet', nome:'Agachamento goblet', grupo:'pernas', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Quadríceps, glúteo, core',
    q:'agachamento goblet execução correta',
    exec:['Segure um halter ou kettlebell junto ao peito.','Pés na largura dos ombros, pontas levemente para fora.','Desça mantendo o tronco ereto e o cotovelo entre os joelhos.','Suba empurrando o chão.'],
    erros:['Inclinar o tronco à frente.','Não descer o suficiente.'] },
  { id:'agachamento-corporal', nome:'Agachamento livre (peso do corpo)', grupo:'pernas', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Quadríceps, glúteo',
    q:'agachamento peso corporal execução correta',
    exec:['Pés na largura dos ombros, braços à frente para equilíbrio.','Empurre o quadril para trás como se fosse sentar.','Desça até a coxa ficar paralela ao chão.','Suba contraindo o glúteo no topo.'],
    erros:['Joelho para dentro.','Tirar o calcanhar do chão.'] },
  { id:'leg-press', nome:'Leg press 45°', grupo:'pernas', tipo:'composto', req:'academia', nivel:1,
    musculos:'Quadríceps, glúteo, posterior',
    q:'leg press 45 execução correta',
    exec:['Apoie os pés na plataforma na largura dos ombros.','Destrave e desça até o joelho formar ~90°.','Não deixe o quadril descolar do apoio.','Empurre sem travar o joelho no topo.'],
    erros:['Descer demais e arredondar a lombar.','Travar o joelho com força no final.'] },
  { id:'cadeira-extensora', nome:'Cadeira extensora', grupo:'pernas', tipo:'isolado', req:'academia', nivel:1,
    musculos:'Quadríceps',
    q:'cadeira extensora execução correta',
    exec:['Ajuste o encosto para o joelho ficar alinhado com o eixo da máquina.','Estenda as pernas até quase travar.','Segure 1 segundo contraindo a coxa.','Desça controlado sem soltar o peso.'],
    erros:['Usar impulso do quadril.','Soltar a fase de descida.'] },
  { id:'mesa-flexora', nome:'Cadeira flexora', grupo:'pernas', tipo:'isolado', req:'academia', nivel:1,
    musculos:'Posterior de coxa',
    q:'cadeira flexora sentada execução correta',
    exec:['Sente com as costas apoiadas e o rolo logo acima do tendão de Aquiles.','Ajuste o apoio das coxas para o joelho não escorregar.','Flexione o joelho puxando o calcanhar para baixo e para trás.','Volte controlado sem estender totalmente.'],
    erros:['Levantar o quadril do assento.','Amplitude curta.'] },
  { id:'stiff-halteres', nome:'Stiff com halteres', grupo:'pernas', tipo:'composto', req:'halteres', nivel:2,
    musculos:'Posterior de coxa, glúteo, lombar',
    q:'stiff com halteres execução correta',
    exec:['Em pé, halteres à frente das coxas, joelho levemente flexionado e fixo.','Empurre o quadril para trás descendo os halteres colados à perna.','Desça até sentir o posterior alongar (sem curvar a lombar).','Volte contraindo o glúteo.'],
    erros:['Dobrar o joelho como num agachamento.','Arredondar as costas.'] },
  { id:'terra-romeno', nome:'Levantamento terra romeno', grupo:'pernas', tipo:'composto', req:'academia', nivel:2,
    musculos:'Posterior de coxa, glúteo, lombar',
    q:'levantamento terra romeno execução correta',
    exec:['Comece em pé com a barra na altura do quadril.','Joelho levemente flexionado, empurre o quadril para trás.','Desça a barra colada à perna até o meio da canela.','Suba estendendo o quadril e contraindo o glúteo.'],
    erros:['Transformar em agachamento.','Deixar a barra longe do corpo.'] },
  { id:'afundo', nome:'Afundo (passada)', grupo:'pernas', tipo:'composto', req:'nenhum', nivel:1, unilateral:true,
    musculos:'Quadríceps, glúteo',
    q:'afundo passada execução correta',
    exec:['Dê um passo à frente mantendo o tronco ereto.','Desça até o joelho de trás quase tocar o chão.','O joelho da frente fica alinhado com o pé.','Empurre com o calcanhar da frente para voltar.'],
    erros:['Passo curto demais (sobrecarrega o joelho).','Inclinar o tronco à frente.'] },
  { id:'bulgaro', nome:'Agachamento búlgaro', grupo:'pernas', tipo:'composto', req:'nenhum', nivel:2, unilateral:true,
    musculos:'Quadríceps, glúteo',
    q:'agachamento búlgaro execução correta',
    exec:['Apoie o peito do pé de trás num banco.','Pé da frente afastado o suficiente para o joelho não passar muito da ponta.','Desça vertical até a coxa da frente ficar paralela.','Suba empurrando o calcanhar da frente.'],
    erros:['Pé da frente muito perto do banco.','Perder o equilíbrio por olhar para baixo.'] },
  { id:'elevacao-pelvica', nome:'Elevação pélvica (hip thrust)', grupo:'pernas', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Glúteo máximo, posterior',
    q:'elevação pélvica hip thrust execução correta',
    exec:['Apoie as costas na borda de um banco ou sofá, pés no chão.','Queixo levemente para baixo, olhar à frente.','Suba o quadril até o tronco ficar paralelo ao chão.','Contraia o glúteo 1 segundo no topo e desça controlado.'],
    erros:['Hiperestender a lombar no topo.','Pés muito perto do corpo (vira quadríceps).'] },
  { id:'step-up', nome:'Subida no banco (step-up)', grupo:'pernas', tipo:'composto', req:'nenhum', nivel:1, unilateral:true,
    musculos:'Quadríceps, glúteo',
    q:'step up subida no banco execução correta',
    exec:['Use um banco na altura do joelho.','Apoie o pé inteiro no banco.','Suba empurrando com a perna de cima, sem impulso da de baixo.','Desça controlado com a mesma perna.'],
    erros:['Dar impulso com a perna de trás.','Banco alto demais.'] },
  { id:'panturrilha-em-pe', nome:'Panturrilha em pé', grupo:'pernas', tipo:'isolado', req:'nenhum', nivel:1,
    musculos:'Gastrocnêmio, sóleo',
    q:'panturrilha em pé execução correta',
    exec:['Fique com a ponta dos pés num degrau, calcanhar livre.','Desça o calcanhar até sentir alongar.','Suba o máximo possível na ponta do pé.','Segure 1 segundo no topo.'],
    erros:['Amplitude curta.','Usar impulso quicando.'] },
  { id:'agachamento-sumo', nome:'Agachamento sumô com halter', grupo:'pernas', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Adutores, glúteo, quadríceps',
    q:'agachamento sumô com halter execução correta',
    exec:['Pés bem mais abertos que os ombros, pontas para fora.','Segure um halter com as duas mãos entre as pernas.','Desça mantendo o tronco ereto e o joelho apontando na direção do pé.','Suba contraindo o glúteo.'],
    erros:['Joelho para dentro.','Inclinar o tronco à frente.'] },

  // ---------------- OMBROS ----------------
  { id:'desenvolvimento-halteres', nome:'Desenvolvimento com halteres', grupo:'ombros', tipo:'composto', req:'halteres', nivel:1,
    musculos:'Deltoide anterior e lateral, tríceps',
    q:'desenvolvimento com halteres ombro execução correta',
    exec:['Sentado ou em pé, halteres na altura das orelhas, palmas para frente.','Trave o core e não hiperestenda a lombar.','Empurre para cima até quase estender o cotovelo.','Desça controlado até a altura da orelha.'],
    erros:['Arquear a lombar para empurrar.','Descer pouco.'] },
  { id:'desenvolvimento-militar', nome:'Desenvolvimento militar com barra', grupo:'ombros', tipo:'composto', req:'academia', nivel:2,
    musculos:'Deltoide, tríceps, core',
    q:'desenvolvimento militar com barra execução correta',
    exec:['Barra na altura da clavícula, mãos pouco mais abertas que os ombros.','Contraia glúteo e abdômen para estabilizar.','Empurre a barra para cima passando a cabeça levemente à frente no topo.','Desça controlado até a clavícula.'],
    erros:['Empurrar com a lombar arqueada.','Deixar a barra à frente da cabeça no topo.'] },
  { id:'elevacao-lateral', nome:'Elevação lateral', grupo:'ombros', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Deltoide lateral',
    q:'elevação lateral halteres execução correta',
    exec:['Em pé, halteres ao lado do corpo, cotovelo levemente flexionado.','Suba os braços para o lado até a altura dos ombros.','Lidere o movimento com o cotovelo, não com a mão.','Desça bem devagar.'],
    erros:['Usar impulso do tronco.','Subir acima da linha do ombro.','Carga pesada demais.'] },
  { id:'elevacao-frontal', nome:'Elevação frontal', grupo:'ombros', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Deltoide anterior',
    q:'elevação frontal halteres execução correta',
    exec:['Halteres à frente das coxas, palmas para o corpo.','Suba um braço de cada vez até a altura do ombro.','Mantenha o tronco parado.','Desça controlado.'],
    erros:['Balançar o tronco.','Subir acima da linha do ombro.'] },
  { id:'crucifixo-inverso', nome:'Crucifixo inverso', grupo:'ombros', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Deltoide posterior, romboides',
    q:'crucifixo inverso halteres execução correta',
    exec:['Incline o tronco à frente mantendo a coluna neutra.','Halteres pendurados com cotovelo levemente flexionado.','Abra os braços para o lado até a linha dos ombros.','Volte controlado.'],
    erros:['Levantar o tronco durante o movimento.','Usar carga alta e virar remada.'] },
  { id:'face-pull', nome:'Face pull', grupo:'ombros', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Deltoide posterior, trapézio médio, manguito rotador',
    q:'face pull execução correta',
    exec:['Elástico ou polia na altura do rosto.','Puxe a corda em direção à testa, separando as mãos.','Cotovelos altos, na linha dos ombros.','Segure 1 segundo e volte controlado.'],
    erros:['Puxar para o peito em vez do rosto.','Deixar o cotovelo cair.'] },
  { id:'pike-push-up', nome:'Flexão pike', grupo:'ombros', tipo:'composto', req:'nenhum', nivel:2,
    musculos:'Deltoide, tríceps',
    q:'flexão pike ombro execução correta',
    exec:['Em posição de V invertido, quadril bem alto.','Desça a cabeça em direção ao chão entre as mãos.','Cotovelo apontando para trás, não para os lados.','Empurre de volta ao topo.'],
    erros:['Quadril baixo (vira flexão comum).','Cotovelo muito aberto.'] },

  // ---------------- BÍCEPS ----------------
  { id:'rosca-direta', nome:'Rosca direta com barra', grupo:'biceps', tipo:'isolado', req:'academia', nivel:1,
    musculos:'Bíceps braquial',
    q:'rosca direta com barra execução correta',
    exec:['Em pé, barra com pegada supinada na largura dos ombros.','Cotovelo colado ao tronco e parado.','Suba a barra contraindo o bíceps.','Desça devagar até quase estender.'],
    erros:['Balançar o tronco.','Mover o cotovelo à frente.'] },
  { id:'rosca-alternada', nome:'Rosca alternada com halteres', grupo:'biceps', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Bíceps braquial, braquial',
    q:'rosca alternada com halteres execução correta',
    exec:['Halteres ao lado do corpo, palmas para dentro.','Suba um braço girando o punho para supinado.','Contraia no topo.','Desça controlado voltando o punho.'],
    erros:['Usar impulso de ombro.','Alternar rápido demais.'] },
  { id:'rosca-martelo', nome:'Rosca martelo', grupo:'biceps', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Braquial, braquiorradial, bíceps',
    q:'rosca martelo execução correta',
    exec:['Halteres ao lado do corpo com palmas voltadas para dentro.','Mantenha essa pegada o movimento inteiro.','Suba até a altura do ombro.','Desça controlado.'],
    erros:['Girar o punho.','Afastar o cotovelo do tronco.'] },
  { id:'rosca-scott', nome:'Rosca scott', grupo:'biceps', tipo:'isolado', req:'academia', nivel:2,
    musculos:'Bíceps braquial (porção curta)',
    q:'rosca scott banco execução correta',
    exec:['Apoie a parte de trás do braço no banco inclinado.','Desça até quase estender o cotovelo.','Suba contraindo sem tirar o braço do apoio.','Controle bem a fase negativa.'],
    erros:['Estender o cotovelo bruscamente no fim.','Levantar o corpo do apoio.'] },

  // ---------------- TRÍCEPS ----------------
  { id:'triceps-corda', nome:'Tríceps na polia com corda', grupo:'triceps', tipo:'isolado', req:'academia', nivel:1,
    musculos:'Tríceps braquial',
    q:'tríceps corda polia execução correta',
    exec:['Fique em pé de frente para a polia alta, cotovelo colado ao tronco.','Estenda o cotovelo abrindo a corda no final.','Segure 1 segundo embaixo.','Volte controlado até ~90°.'],
    erros:['Afastar o cotovelo do corpo.','Inclinar o tronco para empurrar.'] },
  { id:'triceps-testa', nome:'Tríceps testa', grupo:'triceps', tipo:'isolado', req:'halteres', nivel:2,
    musculos:'Tríceps braquial (cabeça longa)',
    q:'tríceps testa execução correta',
    exec:['Deitado, braços estendidos perpendiculares ao corpo.','Dobre só o cotovelo, descendo o peso até a testa.','Mantenha o braço parado.','Estenda de volta sem travar.'],
    erros:['Mover o ombro junto.','Descer rápido demais.'] },
  { id:'triceps-frances', nome:'Tríceps francês com halter', grupo:'triceps', tipo:'isolado', req:'halteres', nivel:1,
    musculos:'Tríceps braquial (cabeça longa)',
    q:'tríceps francês halter execução correta',
    exec:['Sentado ou em pé, segure um halter com as duas mãos acima da cabeça.','Desça atrás da cabeça dobrando só o cotovelo.','Cotovelos apontando para frente e próximos.','Estenda de volta contraindo o tríceps.'],
    erros:['Abrir os cotovelos.','Mover o braço todo.'] },
  { id:'mergulho-banco', nome:'Mergulho no banco', grupo:'triceps', tipo:'composto', req:'nenhum', nivel:1,
    musculos:'Tríceps, deltoide anterior',
    q:'mergulho no banco tríceps execução correta',
    exec:['Mãos apoiadas na borda do banco, dedos para frente.','Pernas estendidas (mais difícil) ou dobradas (mais fácil).','Desça até o cotovelo formar ~90°.','Empurre de volta sem travar.'],
    erros:['Afastar demais o quadril do banco.','Descer fundo e forçar o ombro.'] },
  { id:'triceps-coice', nome:'Tríceps coice', grupo:'triceps', tipo:'isolado', req:'halteres', nivel:1, unilateral:true,
    musculos:'Tríceps braquial',
    q:'tríceps coice halter execução correta',
    exec:['Incline o tronco à frente apoiando uma mão no banco.','Braço colado ao tronco, cotovelo a 90°.','Estenda o cotovelo para trás até o braço ficar reto.','Volte controlado.'],
    erros:['Mover o ombro.','Usar carga alta e perder a posição.'] },

  // ---------------- CORE ----------------
  { id:'prancha', nome:'Prancha isométrica', grupo:'core', tipo:'isometrico', req:'nenhum', nivel:1, tempo:true,
    musculos:'Transverso do abdômen, reto abdominal, lombar',
    q:'prancha abdominal execução correta',
    exec:['Apoie antebraços e pontas dos pés, cotovelo abaixo do ombro.','Corpo em linha reta da cabeça ao calcanhar.','Contraia glúteo e abdômen o tempo todo.','Respire normalmente durante a isometria.'],
    erros:['Quadril alto ou caindo.','Prender a respiração.'] },
  { id:'prancha-lateral', nome:'Prancha lateral', grupo:'core', tipo:'isometrico', req:'nenhum', nivel:1, tempo:true, unilateral:true,
    musculos:'Oblíquos, quadrado lombar',
    q:'prancha lateral execução correta',
    exec:['Deite de lado apoiando o antebraço, cotovelo abaixo do ombro.','Suba o quadril até formar uma linha reta.','Contraia o oblíquo e mantenha.','Troque de lado.'],
    erros:['Deixar o quadril cair.','Girar o tronco.'] },
  { id:'abdominal-supra', nome:'Abdominal supra', grupo:'core', tipo:'isolado', req:'nenhum', nivel:1,
    musculos:'Reto abdominal',
    q:'abdominal supra execução correta',
    exec:['Deite com joelhos dobrados e pés no chão.','Mãos ao lado da cabeça sem puxar o pescoço.','Enrole a coluna tirando as escápulas do chão.','Desça controlado sem relaxar totalmente.'],
    erros:['Puxar a nuca com as mãos.','Usar impulso.'] },
  { id:'elevacao-pernas', nome:'Elevação de pernas', grupo:'core', tipo:'isolado', req:'nenhum', nivel:2,
    musculos:'Reto abdominal inferior, flexores do quadril',
    q:'elevação de pernas abdominal execução correta',
    exec:['Deite com as mãos embaixo do glúteo para proteger a lombar.','Pernas estendidas, suba até 90°.','Desça devagar sem encostar o calcanhar no chão.','Mantenha a lombar colada no chão.'],
    erros:['Descolar a lombar do chão.','Descer rápido demais.'] },
  { id:'dead-bug', nome:'Dead bug', grupo:'core', tipo:'isolado', req:'nenhum', nivel:1,
    musculos:'Core profundo, transverso',
    q:'exercício dead bug execução correta',
    exec:['Deite de barriga para cima, braços apontando para o teto e joelhos a 90°.','Estenda o braço direito e a perna esquerda ao mesmo tempo.','Mantenha a lombar colada no chão.','Volte e alterne os lados.'],
    erros:['Arquear a lombar.','Fazer rápido demais.'] },
  { id:'mountain-climber', nome:'Mountain climber', grupo:'core', tipo:'cardio', req:'nenhum', nivel:1, tempo:true,
    musculos:'Core, ombros, cardio',
    q:'mountain climber execução correta',
    exec:['Posição de prancha alta com as mãos abaixo dos ombros.','Traga um joelho em direção ao peito.','Alterne as pernas em ritmo constante.','Mantenha o quadril baixo e estável.'],
    erros:['Levantar o quadril.','Perder o apoio dos ombros.'] },
  { id:'abdominal-bicicleta', nome:'Abdominal bicicleta', grupo:'core', tipo:'isolado', req:'nenhum', nivel:1,
    musculos:'Reto abdominal, oblíquos',
    q:'abdominal bicicleta execução correta',
    exec:['Deitado, mãos ao lado da cabeça e pernas elevadas.','Leve o cotovelo em direção ao joelho oposto girando o tronco.','Alterne os lados de forma controlada.','Não puxe o pescoço.'],
    erros:['Fazer rápido perdendo a contração.','Puxar a cabeça com as mãos.'] },

  // ---------------- IMPROVISADO (casa, sem equipamento) ----------------
  { id:'remada-toalha-porta', nome:'Remada na porta com toalha', grupo:'costas', tipo:'composto', req:'nenhum', nivel:1, improvisado:true,
    musculos:'Dorsal, romboides, bíceps',
    q:'remada com toalha na porta costas em casa',
    exec:['Passe uma toalha firme em volta de uma maçaneta resistente (porta fechada e travada).','Segure as duas pontas com os braços estendidos e incline o corpo para trás.','Puxe o peito em direção à porta juntando as escápulas.','Volte controlado estendendo os braços.'],
    erros:['Usar porta que abre para o seu lado.','Puxar só com o braço, sem juntar as escápulas.'] },
  { id:'rosca-mochila', nome:'Rosca com mochila', grupo:'biceps', tipo:'isolado', req:'nenhum', nivel:1, improvisado:true,
    musculos:'Bíceps braquial',
    q:'rosca bíceps com mochila em casa execução',
    exec:['Encha uma mochila com livros ou garrafas de água.','Segure a alça com as duas mãos, braços estendidos à frente das coxas.','Cotovelo colado ao tronco, suba a mochila até o peito.','Desça devagar contando 3 segundos.'],
    erros:['Balançar o tronco.','Mover o cotovelo à frente.'] },
  { id:'elevacao-lateral-garrafa', nome:'Elevação lateral com garrafas', grupo:'ombros', tipo:'isolado', req:'nenhum', nivel:1, improvisado:true,
    musculos:'Deltoide lateral',
    q:'elevação lateral com garrafa de água em casa',
    exec:['Segure uma garrafa cheia de água (ou pacote de arroz) em cada mão.','Braços ao lado do corpo, cotovelo levemente flexionado.','Suba para o lado até a altura dos ombros.','Desça bem devagar controlando o peso.'],
    erros:['Usar impulso do tronco.','Subir acima da linha do ombro.'] },

  // ---------------- CARDIO / FINISHER ----------------
  { id:'burpee', nome:'Burpee', grupo:'cardio', tipo:'cardio', req:'nenhum', nivel:2, tempo:true,
    musculos:'Corpo inteiro, condicionamento',
    q:'burpee execução correta',
    exec:['Em pé, agache e apoie as mãos no chão.','Jogue os pés para trás na posição de prancha.','Faça uma flexão (opcional) e volte os pés para perto das mãos.','Salte para cima estendendo o corpo.'],
    erros:['Deixar o quadril cair na prancha.','Perder o controle na descida.'] },
  { id:'polichinelo', nome:'Polichinelo', grupo:'cardio', tipo:'cardio', req:'nenhum', nivel:1, tempo:true,
    musculos:'Condicionamento geral',
    q:'polichinelo jumping jack execução correta',
    exec:['Em pé com os pés juntos e braços ao lado.','Salte abrindo as pernas e levando os braços acima da cabeça.','Volte à posição inicial no salto seguinte.','Mantenha ritmo constante.'],
    erros:['Aterrissar com o joelho travado.','Fazer sem amplitude nos braços.'] },
  { id:'corrida-esteira', nome:'Esteira / caminhada inclinada', grupo:'cardio', tipo:'cardio', req:'academia', nivel:1, tempo:true,
    musculos:'Cardiorrespiratório',
    q:'caminhada inclinada esteira queima de gordura',
    exec:['Comece com 3 a 5 minutos de aquecimento leve.','Ajuste inclinação entre 6% e 12% para caminhada intensa.','Mantenha o tronco ereto, sem se apoiar no painel.','Finalize com 2 a 3 minutos de desaceleração.'],
    erros:['Segurar no apoio o tempo todo.','Inclinação alta com passada curta.'] },
  { id:'pular-corda', nome:'Pular corda', grupo:'cardio', tipo:'cardio', req:'nenhum', nivel:1, tempo:true,
    musculos:'Panturrilha, condicionamento',
    q:'pular corda técnica correta iniciante',
    exec:['Cotovelos próximos ao corpo, giro vem do punho.','Salte apenas 2 a 3 cm do chão.','Aterrisse na ponta dos pés amortecendo.','Mantenha o olhar à frente.'],
    erros:['Saltar alto demais.','Girar com o braço todo.'] }
];
